replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "5.7"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 3306

readinessProbe:
  httpGet:
    path: /
    port: 3306

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-claim
    efs:
      volumeHandle: "fs-0e44751b6665af162"

volumeMounts:
  - name: efs-storage
    mountPath: /var/lib/mysql

nodeSelector: {}

tolerations: []

affinity: {}
